### ISSUE TITLE
[help wanted] every time use toggle_quick_menu the list will flash and then disappear

### ISSUE THREAD

**Issue by shellRaining** [ThePrimeagen/harpoon#366]
hi, this is my first time using this plugin, and the configuration used is as follows

```lua
{
    "ThePrimeagen/harpoon",
    branch = "harpoon2",
    dependencies = {
        "nvim-lua/plenary.nvim",
    },
    config = function()
        local harpoon = require("harpoon")

        harpoon:setup()

        vim.keymap.set("n", "<leader>ha", function()
            harpoon:list():append()
        end)
        vim.keymap.set("n", "<leader>hh", function()
            harpoon.ui:toggle_quick_menu(harpoon:list())
        end)

        vim.keymap.set("n", "<leader>hi", function()
            harpoon:list():select(1)
        end)
        vim.keymap.set("n", "<leader>hj", function()
            harpoon:list():select(2)
        end)
        vim.keymap.set("n", "<leader>hk", function()
            harpoon:list():select(3)
        end)
        vim.keymap.set("n", "<leader>hl", function()
            harpoon:list():select(4)
        end)
    end,
},
```

the plugin manager I used is `lazy`, every time I press `<leader>hh`, the list will flash and disappear, and occasionally the following error will appear.  however, select action has no problem.

https://github.com/ThePrimeagen/harpoon/assets/111564053/bec1a003-c4b8-4dab-bcb8-f7f82fdb7e1d

Is it a configuration problem with me?

**Comment by dozken** [comment]
hey @shellRaining,
I had almost the same configuration as you got, https://github.com/dozken/dozken.nvim/blob/main/lua/plugins/harpoon.lua
and it works fine

**Comment by ThePrimeagen** [comment]
i just added a logger

do you think you could try producing this error given the following steps?
https://github.com/ThePrimeagen/harpoon/tree/harpoon2#logger

**Comment by shellRaining** [comment]
my neovim info as below

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```

follow @daltondiaz step, I create `after/plugin/harpoon.lua`, and paste his code into this file, after add a file to harpoon list, press `<leader>hh`, still flash and the log is 

```
09时38分16秒 msg_show   require("harpoon").logger:show() E5108: Error executing lua ...g/.local/share/nvim/store/harpoon/lua/harpoon/logger.lua:36: 'replacement string' item contains newlines
stack traceback:
	[C]: in function 'nvim_buf_set_lines'
	...g/.local/share/nvim/store/harpoon/lua/harpoon/logger.lua:36: in function 'show'
	[string ":lua"]:1: in main chunk
```

**Comment by ThePrimeagen** [comment]
i am going to fix this issue of not showing the log.  sorry about the delay.  other bugs + the cost of having a family and kids (i tend to bias heavily towards time with them)

**Comment by ThePrimeagen** [comment]
ok, the logger is ready
please open fresh instance of vim, make this happen, and then call `:lua require("harpoon").logger:show()` and copy those contents.

we may need to iterate to work through this

**Comment by shellRaining** [comment]
😂 no matters, the latest version's log is

```
config_default#create_list_item lua/conf/editor/hlchunk.lua
HarpoonList:append { index = -1, item = { context = { col = 0, row = 17 }, value = "lua/conf/editor/hlchunk.lua" } }
ui#toggle_quick_menu __harpoon_files
ui#save { "lua/conf/find/harpoon.lua", "lua/conf/editor/hlchunk.lua" }
toggle by BufWriteCmd
ui#toggle_quick_menu
ui#close_menu name: __harpoon_files win and bufnr { bufnr = 171, win = 1166 }
toggle by BufLeave
ui#toggle_quick_menu
```

the step is

1. open a file named `hlchunk.lua`
2. press `<leader>ha` to append this file to harpoon list
3. press `<leader>hh` to toggle quick menu

**Comment by ThePrimeagen** [comment]
this is strange,

i don't really see why its closing right away.  could you do that again except open the quick menu a few times?  like in the video. and i also pushed a small change to logging so we can see the action taken in toggle quick menu :)

**Comment by shellRaining** [comment]
https://github.com/ThePrimeagen/harpoon/assets/111564053/3c53b641-6435-4a71-a36f-377775edb4fd

and log is below

```
config_default#create_list_item after/plugin/harpoon.lua
HarpoonList:append { index = 4, item = { context = { col = 0, row = 2 }, value = "after/plugin/harpoon.lua" } }
ui#toggle_quick_menu#opening __harpoon_files
ui#save { "lua/conf/find/harpoon.lua", "lua/conf/editor/hlchunk.lua", "init.lua", "after/plugin/harpoon.lua" }
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: __harpoon_files win and bufnr { bufnr = 426, win = 1421 }
toggle by BufLeave
ui#toggle_quick_menu#closing
ui#toggle_quick_menu#opening __harpoon_files
ui#save { "lua/conf/find/harpoon.lua", "lua/conf/editor/hlchunk.lua", "init.lua", "after/plugin/harpoon.lua" }
ui#save { "lua/conf/find/harpoon.lua", "lua/conf/editor/hlchunk.lua", "init.lua", "after/plugin/harpoon.lua" }
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: __harpoon_files win and bufnr { bufnr = 428, win = 1423 }
toggle by BufLeave
ui#toggle_quick_menu#closing
toggle by BufLeave
ui#toggle_quick_menu#closing
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: nil win and bufnr {}
ui#toggle_quick_menu#opening __harpoon_files
ui#save { "lua/conf/find/harpoon.lua", "lua/conf/editor/hlchunk.lua", "init.lua", "after/plugin/harpoon.lua" }
ui#save { "lua/conf/find/harpoon.lua", "lua/conf/editor/hlchunk.lua", "init.lua", "after/plugin/harpoon.lua" }
ui#save { "lua/conf/find/harpoon.lua", "lua/conf/editor/hlchunk.lua", "init.lua", "after/plugin/harpoon.lua" }
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: __harpoon_files win and bufnr { bufnr = 430, win = 1425 }
toggle by BufLeave
ui#toggle_quick_menu#closing
toggle by BufLeave
ui#toggle_quick_menu#closing
toggle by BufLeave
ui#toggle_quick_menu#closing
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: nil win and bufnr {}
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: nil win and bufnr {}
```

the error msg in video is

```
E5108: Error executing lua ...ining/.local/share/nvim/store/harpoon/lua/harpoon/ui.lua:113: attempt to index local 'self' (a nil value)
stack traceback:
        ...ining/.local/share/nvim/store/harpoon/lua/harpoon/ui.lua:113: in function 'toggle_quick_menu'
        [string ":lua"]:1: in main chunk
```

**Comment by daltondiaz** [comment]
I try to reproduce, but works. 

@shellRaining update harpoon, recentily I added the settings because some errors, of course different of your.

```
harpoon:setup({
  settings = {
    save_on_toggle = true
  }
})
```
Maybe works and try to delete harpoon.json

**Comment by shellRaining** [comment]
after add this code and delete harpoon.json, still not work 😢

```
E5108: Error executing lua: ...ining/.local/share/nvim/store/harpoon/lua/harpoon/ui.lua:76: attempt to index field 'settings' (a nil value)
stack traceback:
	...ining/.local/share/nvim/store/harpoon/lua/harpoon/ui.lua:76: in function '_create_window'
	...ining/.local/share/nvim/store/harpoon/lua/harpoon/ui.lua:121: in function 'toggle_quick_menu'
	/Users/shellraining/.config/nvim/lua/conf/find/harpoon.lua:26: in function </Users/shellraining/.config/nvim/lua/conf/find/harpoon.lua:25>
```

**Comment by daltondiaz** [comment]
@shellRaining 

Update the harpoon again, this feature https://github.com/ThePrimeagen/harpoon/pull/392 resolved some errors on UI, maybe fix yours too.

Create the harpoon.json if was not created. 

Example json: 
```json 
{"global_settings":{"enter_on_sendcmd":false,"mark_branch":false,"excluded_filetypes":["harpoon"],"tabline_prefix":"   ","tabline_suffix":"   ","save_on_change":true,"tabline":false,"save_on_toggle":false,"tmux_autoclose_windows":false}}

**Comment by shellRaining** [comment]
```
Error  20时06分45秒 msg_show.emsg E5108: Error executing lua: ...ining/.local/share/nvim/store/harpoon/lua/harpoon/ui.lua:133: attempt to index field 'settings' (a nil value)
stack traceback:
	...ining/.local/share/nvim/store/harpoon/lua/harpoon/ui.lua:133: in function 'toggle_quick_menu'
	/Users/shellraining/.config/nvim/lua/conf/find/harpoon.lua:23: in function </Users/shellraining/.config/nvim/lua/conf/find/harpoon.lua:22>
```

not work for me, error when open quick menu, message above. and `harpoon.json` is (after format)

```json
{
  "/Users/shellraining/Documents/dotfiles/nvim": {
    "__harpoon_files": [
      "{\"context\":{\"row\":28,\"col\":0},\"value\":\"lua\\/conf\\/find\\/harpoon.lua\"}"
    ]
  },
  "/Users/shellraining/.local/share/nvim/store/harpoon": {
    "__harpoon_files": [
      "{\"value\":\".editorconfig\",\"context\":{\"row\":9,\"col\":26}}"
    ]
  }
}
```

I even thought there was an error in my configuration file 😂

```lua
local M = {
    requires = {
        "harpoon",
        "harpoon.ui",
    },
}

function M.load()
    M.harpoon.setup({
        settings = {
            save_on_toggle = true,
        },
    })

    vim.keymap.set("n", "<leader>ha", function()
        M.harpoon:list():append()
    end)
    vim.keymap.set("n", "<leader>hh", function()
        M.harpoon_ui:toggle_quick_menu(M.harpoon:list())
    end)

    vim.keymap.set("n", "<leader>hi", function()
        M.harpoon:list():select(1)
    end)
    vim.keymap.set("n", "<leader>hj", function()
        M.harpoon:list():select(2)
    end)
    vim.keymap.set("n", "<leader>hk", function()
        M.harpoon:list():select(3)
    end)
    vim.keymap.set("n", "<leader>hl", function()
        M.harpoon:list():select(4)
    end)
end

return M
```
the log is 

```
config_default#create_list_item lua/conf/find/harpoon.lua
HarpoonList:append { index = 1, item = { context = { col = 5, row = 22 }, value = "lua/conf/find/harpoon.lua" } }
ui#toggle_quick_menu#opening __harpoon_files
ui#save { "lua/conf/find/harpoon.lua" }
toggle by BufWriteCmd
ui#toggle_quick_menu#closing
ui#close_menu name: __harpoon_files win and bufnr { bufnr = 388, win = 1384 }
toggle by BufLeave
ui#toggle_quick_menu#closing
ui#toggle_quick_menu#closing __harpoon_files
```

**Comment by JustBarnt** [comment]
@shellRaining - Is it possible you have another plugin interfering or perhaps there is a `vim.opt` or `autocmd` you have set that is the issue?

I would suggest backing up your current config, start fresh with just Harpoon and try it. If there is no issue and you see the UI, start adding back pieces of your configuration until you run into the issue again.

**Comment by shellRaining** [comment]
oh yes, it is an auto command caused this problem, I paste below

```lua
if options.auto_save then
    api.nvim_create_autocmd({ "TextChanged", "InsertLeave" }, {
        pattern = { "*" },
        command = "silent! wall",
        nested = true,
    })
end
```

after comment this, work properly!!!

**Comment by JustBarnt** [comment]
@shellRaining Awesome! Glad its fixed!

**Comment by kabra4** [comment]
i also have the same problem however with [auto-save](https://github.com/pocco81/auto-save.nvim). harpoon is working fine when i turn off autosave. is there a way to use harpoon with any auto save?

**Comment by shellRaining** [comment]
api.nvim_create_autocmd({ "TextChanged", "InsertLeave" }, {
        pattern = { "*" },
        callback = function()
            if vim.bo.ft == "harpoon" then
                return
            end
            vim.cmd("silent! wall")
        end,

maybe this can help you

**Comment by ThePrimeagen** [comment]
I'm going to fix this tonight.

If it is autosave I can fix this. I can fix her

**Comment by rootex-** [comment]
@kabra4 this! the same issue with auto-save here, thanks for writing this here.

@ThePrimeagen  fix her 🥇

**Comment by kabra4** [comment]
> @kabra4 this! the same issue with auto-save here, thanks for writing this here. the problem goes away when auto-save is off. 
> 
> @ThePrimeagen  fix her 🥇  

@rootex- use solution provided by @shellRaining, it is working well for now.

**Comment by Andrew15-5** [comment]
The provided solution didn't work, and I have no idea what `options` is (at least I didn't have any `vim.opt.auto_save` set). But it looks hacky regardless. I looked through config settings and remembered the `condition`:

```lua
  condition = function(buf)
    local fn = vim.fn
    local utils = require "auto-save.utils.data"
    if utils.not_in(fn.getbufvar(buf, "&filetype"), { "harpoon" }) then
      return true
    end
    return false
  end,
  -- or
  condition = function(buf)
    return require("auto-save.utils.data").not_in(
      vim.fn.getbufvar(buf, "&filetype"),
      { "harpoon" }
    )
  end,
```

The plugin already have a nice snippet ready to be used. So I just added the filetype to exclude to the list, and now the harpoon menu window doesn't disappear anymore.

https://github.com/okuuva/auto-save.nvim?tab=readme-ov-file#condition

P.S. I'm using this fork because of this: https://github.com/pocco81/auto-save.nvim/issues/80.
